### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by Nobody-11** [Nobody-11/DragonRealmsMod#5]
Anything that have SuperAdmin on them, change it to Admin

And anything that have TelnetAdmin on them, change it to SuperAdmin

Thanks
@Nobody-11

**Comment by DarkCookie108** [comment]
Please Add Me To The Mod repository

**Comment by ThePheonixBlader** [comment]
This is a  bad idea because basically you are copying Camzie's re-made from scratch FOPM

**Comment by Nobody-11** [comment]
Well, I may copying FOPM Remastered but i am going to recode the commands

**Comment by ThePheonixBlader** [comment]
No, you can't remove anything Camzie added.

**Comment by Nobody-11** [comment]
Wow, I dins' import this from FOPN remastered, I made this by my own -.-

Sorry this was sent from my phone
